url: https://github.com/prometheus-community/helm-charts.git
subdirectory: charts/kube-prometheus-stack
commit: 5c36e8e84d96256140d7fae0711d76de5f490e72
version: 80.9.2-rancher.1
additionalCharts:
  - workingDir: charts-crd
    upstreamOptions:
      url: https://github.com/prometheus-community/helm-charts.git
      commit: 5c36e8e84d96256140d7fae0711d76de5f490e72
      subdirectory: charts/kube-prometheus-stack/charts/crds/files
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: monitoring-crd
doNotRelease: false
