tools:
  - name: charts-build-scripts
    version: latest
    source: rancher/charts-build-scripts
    mode: release-checksums

  - name: ob-charts-tool
    # renovate: datasource=github-releases depName=rancher/ob-charts-tool
    version: latest
    source: rancher/ob-charts-tool
    mode: release-checksums
    # Optional overrides for release artifact naming conventions:
    release:
      binary_template: "ob-charts-tool_{os}_{arch}"
      checksum_template: "ob-charts-tool_{version|trimprefix:v}_checksums.txt"

  - name: yq
    mode: pinned
    source: mikefarah/yq
    # renovate: datasource=github-releases depName=mikefarah/yq
    version: v4.52.5
    checksums:
      linux/amd64:  "c529c33e6b545d95e39445c37f673e31ca110c3ca9310b47ccea78f9190b061e"  # renovate-local: yq=v4.52.5
      linux/arm64:  "33cf72426fc5f5e7d9b99801a58d34c6fa7e4426dad594569fb972dde5891109"  # renovate-local: yq=v4.52.5
      darwin/amd64: "672029a24f3038f29fe5fb5a15d600c00ab6affbd5a92e880d3319d629fdee9e"  # renovate-local: yq=v4.52.5
      darwin/arm64: "4613600ee3416000a223f28b5323d3f003ee5bb4c18c5fa916450d31d686aecb"  # renovate-local: yq=v4.52.5
    release:
      binary_template: "yq_{os}_{arch}.tar.gz"
      extract: "yq_{os}_{arch}"

  - name: gh
    mode: pinned
    source: cli/cli
    # renovate: datasource=github-releases depName=cli/cli
    version: v2.89.0
    checksums:
      linux/amd64:  "4613600ee3416000a223f28b5323d3f003ee5bb4c18c5fa916450d31d686aecb"  # renovate-local: gh=v2.89.0
      linux/arm64:  "4613600ee3416000a223f28b5323d3f003ee5bb4c18c5fa916450d31d686aecb"  # renovate-local: gh=v2.89.0
      darwin/amd64: "4613600ee3416000a223f28b5323d3f003ee5bb4c18c5fa916450d31d686aecb"  # renovate-local: gh=v2.89.0
      darwin/arm64: "4613600ee3416000a223f28b5323d3f003ee5bb4c18c5fa916450d31d686aecb"  # renovate-local: gh=v2.89.0
    release:
      binary_template: "gh_{version|trimprefix:v}_{os|replace}_{arch}.tar.gz"
      extract: "bin/gh"

  - name: golangci-lint
    mode: pinned
    source: golangci/golangci-lint
    # renovate: datasource=github-releases depName=golangci/golangci-lint
    version: v2.11.4
    checksums:
      linux/amd64:  "200c5b7503f67b59a6743ccf32133026c174e272b930ee79aa2aa6f37aca7ef1"  # renovate-local: golangci-lint=v2.11.4
      linux/arm64:  "3bcfa2e6f3d32b2bf5cd75eaa876447507025e0303698633f722a05331988db4"  # renovate-local: golangci-lint=v2.11.4
      darwin/amd64: "c900d4048db75d1edfd550fd11cf6a9b3008e7caa8e119fcddbc700412d63e60"  # renovate-local: golangci-lint=v2.11.4
      darwin/arm64: "02db2a2dae8b26812e53b0688a6f617e3ef1f489790e829ea22862cf76945675"  # renovate-local: golangci-lint=v2.11.4
    release:
      binary_template: "golangci-lint-{version|trimprefix:v}-{os}-{arch}.tar.gz"
      extract: "golangci-lint-{version|trimprefix:v}-{os}-{arch}/golangci-lint"
