apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-manifest
  namespace: {{ .Release.Namespace }}
data:
  crds.bz2.b64:
  {{- .Files.Get "monitoring-crd/crds.bz2" | b64enc | indent 4 }}
