#!/usr/bin/env bash

PROJECT_ROOT=$(git rev-parse --show-toplevel)

# Move to the root of the project
cd "$PROJECT_ROOT" || exit

if [[ -f ./bin/ob-charts-tool ]]; then
  exec ./bin/ob-charts-tool getRebaseInfo "$@"
else
  echo "Your ob-charts-tool bin is missing. Run 'dep-fetch sync' to install it."
  exit 1
fi