#!/usr/bin/env bash

PROJECT_ROOT=$(git rev-parse --show-toplevel)

# Move to the root of the project
cd "$PROJECT_ROOT" || exit

if [[ -f ./bin/ob-charts-tool ]]; then
  # Check if there's input from STDIN
  if [ -t 0 ]; then
      # No STDIN, pass all arguments to the command
      exec ./bin/ob-charts-tool verifyChartImages "$@"
  else
      # Pass STDIN to the command
      exec ./bin/ob-charts-tool verifyChartImages "$@" <&0
  fi
else
  echo "Your ob-charts-tool bin is missing. Run 'dep-fetch sync' to install it."
  exit 1
fi
